[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.sdist]
exclude = [
    ".venv",
    "dist",
    ".git",
    "docs/build",
    "sb"
]

[tool.uv-dynamic-versioning]
enable = true
style = "pep440"        # also "semver" or "pvp"
pattern = "default"     # "default" requires a "v" prefix; "default-unprefixed" drops it

[project]
name = "cassis-lte-python"
dynamic = ["version"]  # Remove any static version = "..." line
description = "A python version of the CASSIS LTE modeling tool."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "scipy",
    "astropy",
    "matplotlib",
    "spectral-cube",
    "radio-beam",
    "casa-formats-io",
    "regions",
    "lmfit",
    "emcee",
    "uncertainties",
    "pandas",
    "dask",
    "tqdm",
    "tabulate",
    "natsort",
]

[dependency-groups]
dev = [
    "astroid",
    "pytest",
    "uv-dynamic-versioning>=0.14.0",
]

[project.optional-dependencies]
docs = [
    "sphinx",
    "pydata-sphinx-theme",
    "sphinx-autoapi",
    "sphinx-autodoc-typehints",
    "sphinx-copybutton",
    "sphinx-design",
    "sphinx-prompt",
    "sphinx-tabs",
    "sphinx-toolbox",
]
notebook = [
    "jupyterlab",
    "ipykernel",
    "ipython",
    "notebook",
]

[tool.setuptools.packages.find]
where = ["./"]
include = ["cassis_lte_python"]
exclude = ["docs", "logs", "sb", "tests"]

[tool.setuptools.package-data]
cassis_lte_python = ["settings_defaults.ini"]
